logging:
  level:
    com.kaituo.comparison.back: debug
spring:
  datasource:
    url: jdbc:mysql://139.224.14.200:3306/background?useSSL=false&useUnicode=yes&characterEncoding=UTF8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      max-lifetime: 60000
      maximum-pool-size: 15
  redis:
    host: 139.224.14.200
    port: 6379
#    password: 123456
    timeout: 10000
    pool:
      max-active: 10
      min-idle: 3
      max-idle: 5
  aop:
    proxy-target-class: true
    auto: true
server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024
  port: 1000





#app:
#  id: my-background
#  apollometa: http://config-service-url
#  apollo:
#    bootstrap:
#      enabled: true
#    eagerLoad:
#      enabled: true
#
## web port
#server:
#  port: 8081
#
## log config
#logging:
#  config: classpath:logback.xml
#
#
## xxl-conf
#xxl:
#  conf:
#    admin:
#      address: http://localhost:8080/xxl-conf-admin
#    env: test
#    access:
#      token:
#    mirrorfile: /data/applogs/xxl-conf/xxl-conf-mirror-sample.properties
#
## for test
#test:
#  conf: #{T(com.xxl.conf.core.XxlConfClient).get('default.key02')}

